"""initial

Revision ID: d279475e9d58
Revises: 
Create Date: 2026-01-21 00:15:51.411259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd279475e9d58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_range_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bar', sa.String(length=50), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('range_start', sa.Integer(), nullable=False),
    sa.Column('range_end', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.String(length=255), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('range_spec', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('mode', sa.Enum('FULL', 'INCREMENTAL', name='importmode'), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('source_sheet_id', sa.String(length=255), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_unchanged', sa.Integer(), nullable=False),
    sa.Column('rows_errored', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_key', sa.String(length=64), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('last_import_run_id', sa.Integer(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('bar', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('agent_label', sa.String(length=50), nullable=True),
    sa.Column('staff_id', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('late', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('drinks', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('off', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cut_late', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cut_drink', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cut_other', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contract', sa.String(length=50), nullable=True),
    sa.Column('staff_num_prefix', sa.Integer(), nullable=True),
    sa.Column('agent_id_derived', sa.Integer(), nullable=True),
    sa.Column('agent_mismatch', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_import_run_id'], ['import_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_key')
    )
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('sheet_row_number', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('row_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('sheet_row_number', sa.Integer(), nullable=False),
    sa.Column('row_data', sa.JSON(), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('raw_rows')
    op.drop_table('import_errors')
    op.drop_table('fact_rows')
    op.drop_table('import_runs')
    op.drop_table('data_sources')
    op.drop_table('app_users')
    op.drop_table('agent_range_rules')
    # ### end Alembic commands ###
