"""add_profiles_and_profile_bars_tables

Revision ID: 16f91ab164b4
Revises: contract_types_001
Create Date: 2026-01-31 22:17:18.939758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f91ab164b4'
down_revision: Union[str, None] = 'contract_types_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_type', sa.Enum('STAFF', 'AGENT', name='profiletype'), nullable=False),
    sa.Column('staff_id', sa.String(length=100), nullable=True),
    sa.Column('agent_key', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('picture', sa.LargeBinary(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('line_id', sa.String(length=100), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('facebook', sa.String(length=100), nullable=True),
    sa.Column('tiktok', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('position', sa.Enum('DANCER', 'PR', name='staffposition'), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(profile_type = 'AGENT' AND position IS NULL AND size IS NULL AND weight IS NULL) OR (profile_type = 'STAFF')", name='ck_agent_no_staff_fields'),
    sa.CheckConstraint("(profile_type = 'STAFF' AND staff_id IS NOT NULL AND agent_key IS NULL) OR (profile_type = 'AGENT' AND agent_key IS NOT NULL AND staff_id IS NULL)", name='ck_profile_type_identity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_key'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_index('ix_profiles_agent_key', 'profiles', ['agent_key'], unique=False, postgresql_where=sa.text('agent_key IS NOT NULL'))
    op.create_index('ix_profiles_staff_id', 'profiles', ['staff_id'], unique=False, postgresql_where=sa.text('staff_id IS NOT NULL'))
    op.create_table('profile_bars',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('bar', sa.String(length=50), nullable=False),
    sa.Column('agent_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'bar')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_bars')
    op.drop_index('ix_profiles_staff_id', table_name='profiles', postgresql_where=sa.text('staff_id IS NOT NULL'))
    op.drop_index('ix_profiles_agent_key', table_name='profiles', postgresql_where=sa.text('agent_key IS NOT NULL'))
    op.drop_table('profiles')
    # ### end Alembic commands ###
